# Generated by Django 2.2.4 on 2019-10-06 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikehires',
            name='charges',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='discounts',
            name='date_to',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='UserDiscounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_used', models.DateField(auto_now_add=True)),
                ('amount_saved', models.FloatField()),
                ('discounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.Discounts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bikes.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='discounts',
            field=models.ManyToManyField(through='bikes.UserDiscounts', to='bikes.Discounts'),
        ),
    ]
