# Generated by Django 2.2.4 on 2019-10-06 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_auto_20191006_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discounts',
            name='code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
