# Generated by Django 2.2.4 on 2019-10-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0003_auto_20191006_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discounts',
            old_name='discount_applied',
            new_name='discount_amount',
        ),
    ]
