# Generated by Django 2.2.4 on 2019-10-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0004_auto_20191006_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikehires',
            old_name='bike_id',
            new_name='bike',
        ),
        migrations.RenameField(
            model_name='bikehires',
            old_name='user_id',
            new_name='user',
        ),
    ]
