# Generated by Django 2.2.4 on 2019-10-11 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0005_auto_20191010_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='bikehires',
            name='discount_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.Discounts'),
        ),
    ]
